export const currencyMapping = {
    "United Arab Emirates": { code: "AED", name: "UAE Dirham" },
    "Afghanistan": { code: "AFN", name: "Afghan Afghani" },
    "Albania": { code: "ALL", name: "Albanian Lek" },
    "Armenia": { code: "AMD", name: "Armenian Dram" },
    "Netherlands Antilles": { code: "ANG", name: "Netherlands Antillian Guilder" },
    "Angola": { code: "AOA", name: "Angolan Kwanza" },
    "Argentina": { code: "ARS", name: "Argentine Peso" },
    "Australia": { code: "AUD", name: "Australian Dollar" },
    "Aruba": { code: "AWG", name: "Aruban Florin" },
    "Azerbaijan": { code: "AZN", name: "Azerbaijani Manat" },
    "Bosnia and Herzegovina": { code: "BAM", name: "Bosnia and Herzegovina Mark" },
    "Barbados": { code: "BBD", name: "Barbados Dollar" },
    "Bangladesh": { code: "BDT", name: "Bangladeshi Taka" },
    "Bulgaria": { code: "BGN", name: "Bulgarian Lev" },
    "Bahrain": { code: "BHD", name: "Bahraini Dinar" },
    "Burundi": { code: "BIF", name: "Burundian Franc" },
    "Bermuda": { code: "BMD", name: "Bermudian Dollar" },
    "Brunei": { code: "BND", name: "Brunei Dollar" },
    "Bolivia": { code: "BOB", name: "Bolivian Boliviano" },
    "Brazil": { code: "BRL", name: "Brazilian Real" },
    "Bahamas": { code: "BSD", name: "Bahamian Dollar" },
    "Bhutan": { code: "BTN", name: "Bhutanese Ngultrum" },
    "Botswana": { code: "BWP", name: "Botswana Pula" },
    "Belarus": { code: "BYN", name: "Belarusian Ruble" },
    "Belize": { code: "BZD", name: "Belize Dollar" },
    "Canada": { code: "CAD", name: "Canadian Dollar" },
    "Democratic Republic of the Congo": { code: "CDF", name: "Congolese Franc" },
    "Switzerland": { code: "CHF", name: "Swiss Franc" },
    "Chile": { code: "CLP", name: "Chilean Peso" },
    "China": { code: "CNY", name: "Chinese Renminbi" },
    "Colombia": { code: "COP", name: "Colombian Peso" },
    "Costa Rica": { code: "CRC", name: "Costa Rican Colon" },
    "Cuba": { code: "CUP", name: "Cuban Peso" },
    "Cape Verde": { code: "CVE", name: "Cape Verdean Escudo" },
    "Czech Republic": { code: "CZK", name: "Czech Koruna" },
    "Djibouti": { code: "DJF", name: "Djiboutian Franc" },
    "Denmark": { code: "DKK", name: "Danish Krone" },
    "Dominican Republic": { code: "DOP", name: "Dominican Peso" },
    "Algeria": { code: "DZD", name: "Algerian Dinar" },
    "Egypt": { code: "EGP", name: "Egyptian Pound" },
    "Eritrea": { code: "ERN", name: "Eritrean Nakfa" },
    "Ethiopia": { code: "ETB", name: "Ethiopian Birr" },
    "European Union": { code: "EUR", name: "Euro" },
    "Fiji": { code: "FJD", name: "Fiji Dollar" },
    "Falkland Islands": { code: "FKP", name: "Falkland Islands Pound" },
    "Faroe Islands": { code: "FOK", name: "Faroese Króna" },
    "United Kingdom": { code: "GBP", name: "Pound Sterling" },
    "Georgia": { code: "GEL", name: "Georgian Lari" },
    "Guernsey": { code: "GGP", name: "Guernsey Pound" },
    "Ghana": { code: "GHS", name: "Ghanaian Cedi" },
    "Gibraltar": { code: "GIP", name: "Gibraltar Pound" },
    "The Gambia": { code: "GMD", name: "Gambian Dalasi" },
    "Guinea": { code: "GNF", name: "Guinean Franc" },
    "Guatemala": { code: "GTQ", name: "Guatemalan Quetzal" },
    "Guyana": { code: "GYD", name: "Guyanese Dollar" },
    "Hong Kong": { code: "HKD", name: "Hong Kong Dollar" },
    "Honduras": { code: "HNL", name: "Honduran Lempira" },
    "Croatia": { code: "HRK", name: "Croatian Kuna" },
    "Haiti": { code: "HTG", name: "Haitian Gourde" },
    "Hungary": { code: "HUF", name: "Hungarian Forint" },
    "Indonesia": { code: "IDR", name: "Indonesian Rupiah" },
    "Israel": { code: "ILS", name: "Israeli New Shekel" },
    "Isle of Man": { code: "IMP", name: "Manx Pound" },
    "India": { code: "INR", name: "Indian Rupee" },
    "Iraq": { code: "IQD", name: "Iraqi Dinar" },
    "Iran": { code: "IRR", name: "Iranian Rial" },
    "Iceland": { code: "ISK", name: "Icelandic Króna" },
    "Jersey": { code: "JEP", name: "Jersey Pound" },
    "Jamaica": { code: "JMD", name: "Jamaican Dollar" },
    "Jordan": { code: "JOD", name: "Jordanian Dinar" },
    "Japan": { code: "JPY", name: "Japanese Yen" },
    "Kenya": { code: "KES", name: "Kenyan Shilling" },
    "Kyrgyzstan": { code: "KGS", name: "Kyrgyzstani Som" },
    "Cambodia": { code: "KHR", name: "Cambodian Riel" },
    "Kiribati": { code: "KID", name: "Kiribati Dollar" },
    "Comoros": { code: "KMF", name: "Comorian Franc" },
    "South Korea": { code: "KRW", name: "South Korean Won" },
    "Kuwait": { code: "KWD", name: "Kuwaiti Dinar" },
    "Cayman Islands": { code: "KYD", name: "Cayman Islands Dollar" },
    "Kazakhstan": { code: "KZT", name: "Kazakhstani Tenge" },
    "Laos": { code: "LAK", name: "Lao Kip" },
    "Lebanon": { code: "LBP", name: "Lebanese Pound" },
    "Sri Lanka": { code: "LKR", name: "Sri Lanka Rupee" },
    "Liberia": { code: "LRD", name: "Liberian Dollar" },
    "Lesotho": { code: "LSL", name: "Lesotho Loti" },
    "Libya": { code: "LYD", name: "Libyan Dinar" },
    "Morocco": { code: "MAD", name: "Moroccan Dirham" },
    "Moldova": { code: "MDL", name: "Moldovan Leu" },
    "Madagascar": { code: "MGA", name: "Malagasy Ariary" },
    "North Macedonia": { code: "MKD", name: "Macedonian Denar" },
    "Myanmar": { code: "MMK", name: "Burmese Kyat" },
    "Mongolia": { code: "MNT", name: "Mongolian Tögrög" },
    "Macau": { code: "MOP", name: "Macanese Pataca" },
    "Mauritania": { code: "MRU", name: "Mauritanian Ouguiya" },
    "Mauritius": { code: "MUR", name: "Mauritian Rupee" },
    "Maldives": { code: "MVR", name: "Maldivian Rufiyaa" },
    "Malawi": { code: "MWK", name: "Malawian Kwacha" },
    "Mexico": { code: "MXN", name: "Mexican Peso" },
    "Malaysia": { code: "MYR", name: "Malaysian Ringgit" },
    "Mozambique": { code: "MZN", name: "Mozambican Metical" },
    "Namibia": { code: "NAD", name: "Namibian Dollar" },
    "Nigeria": { code: "NGN", name: "Nigerian Naira" },
    "Nicaragua": { code: "NIO", name: "Nicaraguan Córdoba" },
    "Norway": { code: "NOK", name: "Norwegian Krone" },
    "Nepal": { code: "NPR", name: "Nepalese Rupee" },
    "New Zealand": { code: "NZD", name: "New Zealand Dollar" },
    "Oman": { code: "OMR", name: "Omani Rial" },
    "Panama": { code: "PAB", name: "Panamanian Balboa" },
    "Peru": { code: "PEN", name: "Peruvian Sol" },
    "Papua New Guinea": { code: "PGK", name: "Papua New Guinean Kina" },
    "Philippines": { code: "PHP", name: "Philippine Peso" },
    "Pakistan": { code: "PKR", name: "Pakistani Rupee" },
    "Poland": { code: "PLN", name: "Polish Złoty" },
    "Paraguay": { code: "PYG", name: "Paraguayan Guaraní" },
    "Qatar": { code: "QAR", name: "Qatari Riyal" },
    "Romania": { code: "RON", name: "Romanian Leu" },
    "Serbia": { code: "RSD", name: "Serbian Dinar" },
    "Russia": { code: "RUB", name: "Russian Ruble" },
    "Rwanda": { code: "RWF", name: "Rwandan Franc" },
    "Saudi Arabia": { code: "SAR", name: "Saudi Riyal" },
    "Solomon Islands": { code: "SBD", name: "Solomon Islands Dollar" },
    "Seychelles": { code: "SCR", name: "Seychellois Rupee" },
    "Sudan": { code: "SDG", name: "Sudanese Pound" },
    "Sweden": { code: "SEK", name: "Swedish Krona" },
    "Singapore": { code: "SGD", name: "Singapore Dollar" },
    "Saint Helena": { code: "SHP", name: "Saint Helena Pound" },
    "Sierra Leone": { code: "SLE", name: "Sierra Leonean Leone" },
    "Somalia": { code: "SOS", name: "Somali Shilling" },
    "Suriname": { code: "SRD", name: "Surinamese Dollar" },
    "South Sudan": { code: "SSP", name: "South Sudanese Pound" },
    "São Tomé and Príncipe": { code: "STN", name: "São Tomé and Príncipe Dobra" },
    "Syria": { code: "SYP", name: "Syrian Pound" },
    "Eswatini": { code: "SZL", name: "Eswatini Lilangeni" },
    "Thailand": { code: "THB", name: "Thai Baht" },
    "Tajikistan": { code: "TJS", name: "Tajikistani Somoni" },
    "Turkmenistan": { code: "TMT", name: "Turkmenistan Manat" },
    "Tunisia": { code: "TND", name: "Tunisian Dinar" },
    "Tonga": { code: "TOP", name: "Tongan Paʻanga" },
    "Turkey": { code: "TRY", name: "Turkish Lira" },
    "Trinidad and Tobago": { code: "TTD", name: "Trinidad and Tobago Dollar" },
    "Tuvalu": { code: "TVD", name: "Tuvaluan Dollar" },
    "Taiwan": { code: "TWD", name: "New Taiwan Dollar" },
    "Tanzania": { code: "TZS", name: "Tanzanian Shilling" },
    "Ukraine": { code: "UAH", name: "Ukrainian Hryvnia" },
    "Uganda": { code: "UGX", name: "Ugandan Shilling" },
    "United States": { code: "USD", name: "United States Dollar" },
    "Uruguay": { code: "UYU", name: "Uruguayan Peso" },
    "Uzbekistan": { code: "UZS", name: "Uzbekistani So'm" },
    "Venezuela": { code: "VES", name: "Venezuelan Bolívar Soberano" },
    "Vietnam": { code: "VND", name: "Vietnamese Đồng" },
    "Vanuatu": { code: "VUV", name: "Vanuatu Vatu" },
    "Samoa": { code: "WST", name: "Samoan Tālā" },
    "CEMAC": { code: "XAF", name: "Central African CFA Franc" },
    "Organisation of Eastern Caribbean States": { code: "XCD", name: "East Caribbean Dollar" },
    "International Monetary Fund": { code: "XDR", name: "Special Drawing Rights" },
    "CFA": { code: "XOF", name: "West African CFA franc" },
    "Collectivités d'Outre-Mer": { code: "XPF", name: "CFP Franc" },
    "Yemen": { code: "YER", name: "Yemeni Rial" },
    "South Africa": { code: "ZAR", name: "South African Rand" },
    "Zambia": { code: "ZMW", name: "Zambian Kwacha" },
    "Zimbabwe": { code: "ZWL", name: "Zimbabwean Dollar" }
  };
  